framework:
  translator:
    paths: ['%kernel.project_dir%/vendor/ivovalchev/edit-this-page/translations']

twig:
  paths: ['%kernel.project_dir%/templates/bundles/edit-this-page', '%kernel.project_dir%/vendor/ivovalchev/edit-this-page/templates']
